#%RAML 1.0 DataType
type: object
properties: 
  customerNumber:
    description: CSS Customer Number
    type: integer
    required: true
    minimum: 0
    maximum: 999999999
  address:
    description: CSS Customer Address
    type: !include ../common/address/CommunicationMailingAddress.raml
    required: true