#%RAML 1.0 DataType
properties:
  billMonth:
    description: Billing month
    type: datetime
    required: false
  startDate:
    description: Start date of billing
    type: datetime
    required: false
  endDate:
    description: End date of billing
    type: datetime
    required: false
  quantityUsage:
    description: Usage quantity
    type: number
    required: false
  averageTemperature:
    description: Average temperature
    type: number
    required: false
  showCostPerDay:
    description: Cost per day flag
    type: boolean
    required: false
  costPerDay:
    description: Cost per day
    type: number
    required: false
  daysInPeriod:
    description: Number of days in period
    type: integer
    required: false