#%RAML 1.0 DataType
type: object
properties:
  deliveryVoltage:
    description: DeliveryVoltage
    type: string
    required: false
  supplyVoltage:
    description: SupplyVoltage
    type: string
    required: false
  meterVoltage:
    description: MeterVoltage
    type: string
    required: false
  transformerOwnership:
    description: TransformerOwnership
    type: string
    required: false