#%RAML 1.0 NamedExample
value:
  billAccountNumber: 101
  address:
    addressID: 123
    addressType:
      addressTypeID: 'H'
      description: 'home'
    isReadOnly: true
    addressDetails:
      addressLine1: '1901 Chouteau Ave'
      addressLine2: 'line 2'
      addressLine3: 'line 3'
      city: 'St. Louis'
      state: 'MO'
      postalCode: '63105'
      country: 'US'