#%RAML 1.0 NamedExample
value:
  phoneID: 1
  phoneType: 'H'
  isPrimary: true
  isUnlisted: false
  isTextable: true
  phoneNumberDetails:
    areaCode: '516'
    mainNumber: '5555555'
    extension: '101'