#%RAML 1.0 DataType
type: object
properties:
  currentSupplyTypeCode:
    description: CurrentSupplyTypeCode
    type: string
    required: false
  currentSupplyTypeDescription:
    description: CurrentSupplyTypeDescription
    type: string
    required: false
  futureSupplyTypeCode:
    description: FutureSupplyTypeCode
    type: string
    required: false
  futureSupplyTypeDescription:
    description: FutureSupplyTypeDescription
    type: string
    required: false
  eligibleSwitchDate:
    description: EligibleSwitchDate
    type: string
    required: false