#%RAML 1.0 DataType
type: object
properties: 
  deliveryVoltageCode:
    description: Delivery Voltage Code
    type: string
    required: false
  deliveryVoltageDescription:
    description: Delivery Voltage Description
    type: string
    required: false
  deliveryVoltageDescriptionARES:
    description: Delivery Voltage Description ARES
    type: string
    required: false
  supplyVoltageCode:
    description: Supply Voltage Code
    type: string
    required: false
  supplyVoltageDescription:
    description: Supply Voltage Description
    type: string
    required: false
  supplyVoltageDescriptionARES:
    description: Supply Voltage Description ARES
    type: string
    required: false
  meteringTypeCode:
    description: Metering Type Code
    type: string
    required: false
  meteringTypeDescription:
    description: Metering Type Description
    type: string
    required: false
  meteringTypeDescriptionARES:
    description: Metering Type Description ARES
    type: string
    required: false
  profileClass:
    description: ProfileClass
    type: string
    required: false
  mvGroupCode:
    description: MvGroupCode
    type: string
    required: false
  mvGroupDecode:
    description: MvGroupDecode
    type: string
    required: false
  hasTransformationCharge:
    description: HasTransformationCharge
    type: boolean
    required: false
  effectivePLC:
    description: EffectivePLC
    type: number
    required: false