#%RAML 1.0 DataType
type: object
properties:
 accountNumber:
     description:
     type: number
     required: false
 premiseNumber:
     description:
     type: number
     required: false
 customerNumber:
     description:
     type: number
     required: false
 addresstypeCode:
     description:
     type: string
     required: false
 addressID:
     description:
     type: number
     required: false
 primaryPhoneID:
     description:
     type: number
     required: false
 secondaryPhoneID:
     description:
     type: number
     required: false
 accountStatusCode:
     description:
     type: string
     required: false
 accountStatusDescription:
     description:
     type: string
     required: false
 revenueClassCode:
     description:
     type: string
     required: false
 revenueClassDescription:
     description:
     type: string
     required: false
 tariffTypeCode:
     description:
     type: string
     required: false
 tariffTypeDescription:
     description:
     type: string
     required: false
 accountTypeCode:
     description:
     type: string
     required: false
 accountTypeDescription:
     description:
     type: string
     required: false
 weatherGroupCode:
     description:
     type: string
     required: false
 weatherGroupDescription:
     description:
     type: string
     required: false
 billGroup:
     description:
     type: number
     required: false
 dateLastBilled:
     description:
     type: string
     required: false
 dateNextBilled:
     description:
     type: string
     required: false
 summarySubordinate:
     description:
     type: string
     required: false
 customerSegmentCode:
     description:
     type: string
     required: false
 customerSegmentDescription:
     description:
     type: string
     required: false
 accountHandlingCode:
     description:
     type: string
     required: false
 accountHandlingDescription:
     description:
     type: string
     required: false